export type TaskModel = {
    id: number,
    title: string,
    description?: string,
    startTime: Date,
    endTime: Date,
    File?: File[] | FileList,
    tags?: string,
    priority: "low" | "medium" | "high",
    isDone: boolean,
    isAllDay:boolean,
    categoryId?: number,
}
export type DexieTaskModel = {
    id: number,
    title: string,
    description?: string,
    startTime: number,
    endTime: number,
    File?: File[] | FileList,
    tags?: string,
    priority: "low" | "medium" | "high",
    isDone: boolean,
    isAllDay:boolean,
    categoryId?: number,
}
